# Generated by Django 2.2.24 on 2023-04-18 12:16

import phonenumbers
from django.db import migrations


COUNTRY_CODE = 'RU'


def normalize_phonenumber(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        owner_pure_phone = phonenumbers.parse(flat.owners_phonenumber, COUNTRY_CODE)
        if phonenumbers.is_valid_number(owner_pure_phone):
            flat.owner_pure_phone = owner_pure_phone
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(normalize_phonenumber),
    ]
