# Generated by Django 2.2.24 on 2023-04-18 14:35

from django.db import migrations, models


def copy_flats_to_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        owner.flats.set(Flat.objects.filter(owner=owner.name))


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20230418_1627'),
    ]

    operations = [
        migrations.RunPython(copy_flats_to_owners),

        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='ФИО владельца'),
        ),
    ]
